# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1668AtrfmxpZpXtpOKPsCsKkqh_KjrNPi

BASIC E CHALLAN
"""

rules = {
    1: {"rule": "signal break", "fine": 1000},
    2: {"rule": "speeding", "fine": 500},
    3: {"rule": "overspeeding", "fine": 3000}
  }

print("======E-CHALLAN SYSTEM======")

#input from user
name = input("enter driver name: ")
vehicle = input("enter vehicle number: ")

print("\n------traffic rules------")
print("1 - Signal break (Rs. 2000)")
print("2 - Speeding (Rs. 500)")
print("3 - Overspeeding (Rs. 3000)")

choice = int(input("\nEnter rule number: "))

#if else condition
if choice in rules:
  print("\n---E-challan Generated---")
  print("Driver name:", name)
  print("Vehicle number:", vehicle)
  print("Violation:", rules[choice]["rule"])
  print("Fine amount: rs", rules[choice]["fine"])
  print("")
else:
  print("\n  invalid rule selected!")